# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: DuckStudio.GitHubView
PackageVersion: 1.0.3
NestedInstallerFiles:
- RelativeFilePath: ghv.exe
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- ghv
Protocols:
- https
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.Runtime.8
ReleaseDate: 2025-02-23
Installers:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/DuckDuckStudio/GitHubView/releases/download/1.0.3/GitHubView-1.0.3-windows-latest.zip
  InstallerSha256: 3B43AE9AEEB3F9832D916E8DDC0CDA64265B06840B80DC8685D6447CEF888348
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/DuckDuckStudio/GitHubView/releases/download/1.0.3/GitHubView-1.0.3-windows-latest.zip
  InstallerSha256: 3B43AE9AEEB3F9832D916E8DDC0CDA64265B06840B80DC8685D6447CEF888348
- Architecture: arm
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/DuckDuckStudio/GitHubView/releases/download/1.0.3/GitHubView-1.0.3-windows-latest.zip
  InstallerSha256: 3B43AE9AEEB3F9832D916E8DDC0CDA64265B06840B80DC8685D6447CEF888348
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  InstallerUrl: https://github.com/DuckDuckStudio/GitHubView/releases/download/1.0.3/GitHubView-1.0.3-windows-latest.zip
  InstallerSha256: 3B43AE9AEEB3F9832D916E8DDC0CDA64265B06840B80DC8685D6447CEF888348
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/DuckDuckStudio/GitHubView/releases/download/1.0.3/GitHubView-1.0.3-windows-latest.zip
  InstallerSha256: 3B43AE9AEEB3F9832D916E8DDC0CDA64265B06840B80DC8685D6447CEF888348
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://github.com/DuckDuckStudio/GitHubView/releases/download/1.0.3/GitHubView-1.0.3-windows-latest.zip
  InstallerSha256: 3B43AE9AEEB3F9832D916E8DDC0CDA64265B06840B80DC8685D6447CEF888348
- Architecture: arm
  InstallerType: inno
  InstallerUrl: https://github.com/DuckDuckStudio/GitHubView/releases/download/1.0.3/GitHubView-1.0.3-windows-latest.zip
  InstallerSha256: 3B43AE9AEEB3F9832D916E8DDC0CDA64265B06840B80DC8685D6447CEF888348
- Architecture: arm64
  InstallerType: inno
  InstallerUrl: https://github.com/DuckDuckStudio/GitHubView/releases/download/1.0.3/GitHubView-1.0.3-windows-latest.zip
  InstallerSha256: 3B43AE9AEEB3F9832D916E8DDC0CDA64265B06840B80DC8685D6447CEF888348
ManifestType: installer
ManifestVersion: 1.9.0
