# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: JesseDuffield.lazygit
PackageVersion: 0.47.1
PackageLocale: en-US
Publisher: Jesse Duffield
PublisherUrl: https://github.com/jesseduffield
PublisherSupportUrl: https://github.com/jesseduffield/lazygit/issues
Author: Jesse Duffield
PackageName: lazygit
PackageUrl: https://github.com/jesseduffield/lazygit
License: MIT
LicenseUrl: https://github.com/jesseduffield/lazygit/blob/HEAD/LICENSE
Copyright: Copyright (c) 2018 Jesse Duffield
CopyrightUrl: https://raw.githubusercontent.com/jesseduffield/lazygit/master/LICENSE
ShortDescription: Simple terminal UI for git commands.
Moniker: lazygit
Tags:
- cli
- cross-platform
- git
- git-client
- open-source
- terminal-app
ReleaseNotes: |-
  What's Changed
  Maintenance ⚙️
  - Fix race condition with reselecting the focused branch and rendering by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4268
  Full Changelog: https://github.com/jesseduffield/lazygit/compare/v0.47.0...v0.47.1
ReleaseNotesUrl: https://github.com/jesseduffield/lazygit/releases/tag/v0.47.1
ManifestType: defaultLocale
ManifestVersion: 1.9.0
