# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: JesseDuffield.lazygit
PackageVersion: 0.47.1
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: lazygit.exe
ReleaseDate: 2025-02-22
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/jesseduffield/lazygit/releases/download/v0.47.1/lazygit_0.47.1_Windows_32-bit.zip
  InstallerSha256: 3CADA6F0D28D733B6343391F81FD95038A4940C6C24BBD03FA15D6260789FBAF
- Architecture: x64
  InstallerUrl: https://github.com/jesseduffield/lazygit/releases/download/v0.47.1/lazygit_0.47.1_Windows_x86_64.zip
  InstallerSha256: 5E0F5D6DF89BEB0B84CDC0EAC1B3DC7B6061EBE47EC856BD0710610B82527D9D
- Architecture: arm64
  InstallerUrl: https://github.com/jesseduffield/lazygit/releases/download/v0.47.1/lazygit_0.47.1_Windows_arm64.zip
  InstallerSha256: 1317B604958EFD0E28C266F2A95257C80C4E109DC105F560711B65FD0A41D430
- Architecture: neutral
  InstallerUrl: https://github.com/jesseduffield/lazygit/releases/download/v0.47.1/lazygit_0.47.1_Windows_armv6.zip
  InstallerSha256: 9F0B2298FF497228D0BDCC5221EB60C69A0297E16395307912B254A6B7038A57
ManifestType: installer
ManifestVersion: 1.9.0
