# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: ONLYOFFICE.DesktopEditors
PackageVersion: 8.3.1
InstallerLocale: en-US
UpgradeBehavior: install
FileExtensions:
- csv
- djvu
- doc
- docm
- docx
- docxf
- dot
- dotm
- dotx
- epub
- fb2
- html
- odp
- ods
- odt
- otp
- ots
- ott
- oxps
- pdf
- pot
- potm
- potx
- pps
- ppsm
- ppt
- pptm
- pptx
- rtf
- txt
- xls
- xlsb
- xlsm
- xlsx
- xltm
- xltx
- xml
- xps
ReleaseDate: 2025-02-28
Installers:
- Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v8.3.1/DesktopEditors_x86.msi
  InstallerSha256: 38B975A7CE70638C0629BF6E0C5FE868A1E48C1CFD5A9F43BEC6DD4B39F69A61
  ProductCode: '{FA186017-279E-7406-5D62-ED78556C1419}'
  AppsAndFeaturesEntries:
  - DisplayName: ONLYOFFICE
    Publisher: Ascensio System SIA
    DisplayVersion: 8.3.1.25
    ProductCode: '{FA186017-279E-7406-5D62-ED78556C1419}'
    UpgradeCode: '{47EEF706-B0E4-4C43-944B-E5F914B92B79}'
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v8.3.1/DesktopEditors_x86.msi
  InstallerSha256: 38B975A7CE70638C0629BF6E0C5FE868A1E48C1CFD5A9F43BEC6DD4B39F69A61
  ProductCode: '{FA186017-279E-7406-5D62-ED78556C1419}'
  AppsAndFeaturesEntries:
  - DisplayName: ONLYOFFICE
    Publisher: Ascensio System SIA
    DisplayVersion: 8.3.1.25
    ProductCode: '{FA186017-279E-7406-5D62-ED78556C1419}'
    UpgradeCode: '{47EEF706-B0E4-4C43-944B-E5F914B92B79}'
  ElevationRequirement: elevatesSelf
- Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v8.3.1/DesktopEditors_x64.msi
  InstallerSha256: 4962810570A66F97EF3295119E0E4BC6F1681AA4C0092F9760446EB5DA9FECC0
  ProductCode: '{BCD0F16A-6306-A9BA-5740-C04AE87E9AB3}'
  AppsAndFeaturesEntries:
  - DisplayName: ONLYOFFICE
    Publisher: Ascensio System SIA
    DisplayVersion: 8.3.1.25
    ProductCode: '{BCD0F16A-6306-A9BA-5740-C04AE87E9AB3}'
    UpgradeCode: '{47EEF706-B0E4-4C43-944B-E5F914B92B79}'
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v8.3.1/DesktopEditors_x64.msi
  InstallerSha256: 4962810570A66F97EF3295119E0E4BC6F1681AA4C0092F9760446EB5DA9FECC0
  ProductCode: '{BCD0F16A-6306-A9BA-5740-C04AE87E9AB3}'
  AppsAndFeaturesEntries:
  - DisplayName: ONLYOFFICE
    Publisher: Ascensio System SIA
    DisplayVersion: 8.3.1.25
    ProductCode: '{BCD0F16A-6306-A9BA-5740-C04AE87E9AB3}'
    UpgradeCode: '{47EEF706-B0E4-4C43-944B-E5F914B92B79}'
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.9.0
