# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Barry-ran.QtScrcpy
PackageVersion: 3.1.1
PackageLocale: en-US
Publisher: Barry
PublisherUrl: https://github.com/barry-ran
PublisherSupportUrl: https://github.com/barry-ran/QtScrcpy
PrivacyUrl: https://github.com/barry-ran/QtScrcpy
Author: barry-ran
PackageName: QtScrcpy
PackageUrl: https://github.com/barry-ran/QtScrcpy
License: Apache-2.0 license
LicenseUrl: https://github.com/barry-ran/QtScrcpy/blob/dev/LICENSE
CopyrightUrl: https://github.com/barry-ran/QtScrcpy/blob/dev/LICENSE
ShortDescription: Android real-time display control software
ReleaseNotes: 'fix: mac arm version error fix: qt6 render black'
ReleaseNotesUrl: https://github.com/barry-ran/QtScrcpy/releases/tag/v3.1.1
ManifestType: defaultLocale
ManifestVersion: 1.9.0
