# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.9.0.schema.json

PackageIdentifier: Barry-ran.QtScrcpy
PackageVersion: 3.1.2
PackageLocale: zh-CN
Publisher: Barry
PublisherUrl: https://github.com/barry-ran
PublisherSupportUrl: https://github.com/barry-ran/QtScrcpy
PrivacyUrl: https://github.com/barry-ran/QtScrcpy
Author: barry-ran
PackageName: QtScrcpy
PackageUrl: https://github.com/barry-ran/QtScrcpy
License: Apache-2.0 license
LicenseUrl: https://github.com/barry-ran/QtScrcpy/blob/dev/LICENSE
CopyrightUrl: https://github.com/barry-ran/QtScrcpy/blob/dev/LICENSE
ShortDescription: 安卓实时显示控制软件
ReleaseNotesUrl: https://github.com/barry-ran/QtScrcpy/releases/tag/v3.1.2
ManifestType: locale
ManifestVersion: 1.9.0
